name: ExpHolder
version: '${project.version}'
main: me.architetto.expholder.ExpHolder
api-version: 1.18
authors: [ Architetto ]
commands:
  expholder:
    description: expholder command

permissions:
  expholder.deposit:
    description: deposit command permission
    default: true
  expholder.withdraw:
    description: withdraw command permission
    default: true
  expholder.check:
    description: check command permission
    default: true
  expholder.list:
    description: list command permission
    default: op
